### ISSUE TITLE
Red highlighted unread

### ISSUE THREAD

**Issue by ben-rube** [rocketman10404/tabbychat#25]
![screen shot 2013-10-14 at 4 50 25 pm](https://f.cloud.github.com/assets/5686050/1329176/4a43bc70-3512-11e3-98fd-46693d3bf1a1.png)
I have it set to off and it still sends the the unread altert

**Comment by rocketman10404** [comment]
Each tab has its own individual 'unread notification' setting, which can be accessed by right-clicking on the tab.  The setting you're showing in your screenshot simply controls whether or not that option is enabled on newly-created tabs, it won't change the setting for current tabs.

Let me know if that's not working as I just described, or if changing the setting for each tab doesn't have the desired effect.  I'll confirm myself the next time I have the opportunity.

**Comment by ben-rube** [comment]
THANK YOU SO MUCH!!!!
