### ISSUE TITLE
Chatbox remains open after hitting enter

### ISSUE THREAD

**Issue by Superchicken** [rocketman10404/tabbychat#28]
The chatbox stays open after hitting enter, regardless of whether or not there is text to send.

Normally hitting enter would send the current message then close the chatbox or, if there was no current message, hitting enter would just close the chat box

minecraft: 1.6.4
tabbychat: 1.9.02
liteloader: 1.6.4-01

**Comment by Superchicken** [comment]
I should add that hitting the escape key is how you exit the chatbox

**Comment by Superchicken** [comment]
This issue only occurs with the litemod file from the minecraft forum post, grabbing the tabbychat litemod file from an installed voxelmodpack fixes this issue. Please mark as fixed after the minecraft forum post is updated with a working mod file.

**Comment by rocketman10404** [comment]
The litemod file used in the voxelmodpack should be the same file as found in the minecraft forum post (they were downloaded from the same link).  Can you check and make sure your chatbox is not currently pinned open?  This sounds like the intended behavior for a pinned-open chatbox.

**Comment by Superchicken** [comment]
You are correct, the chatbox was pinned open, I did not know that was a feature. Changing the tabbychat litemod file to an untouched one may have reset the pinned status to unpinned, or it may have been something else I was fooling around with. Regardless, I can reproduce the "bug" mentioned in the original post by re-pinning the chatbox and resolve it by un-pinning the chatbox. I feel silly now.
